spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:6603/cloud_order?useSSL=false
    username: FlanChan
    password: wingofmystery

mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true

# eurake注册中心相关配置
#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:10086/eureka
##启用饥饿加载，在服务启动时就加载服务资源
#ribbon:
#  eager-load:
#    enabled: true
#    clients:
#      - userservice