server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:6603/heima
    username: FlanChan
    password: wingofmystery
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: cn.itcast.hotel.pojo